name: Integration Continue

run-name: ${{ github.actor }} is learning GitHub Actions

on:
  push:
    branches:
      - cicd
      - develop
  pull_request:
    branches:
      - cicd
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21.0.1
        uses: actions/setup-java@v3
        with:
          java-version: '21.0.1'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run tests
        run: mvn test
